Accueil:
  path: /
  controller: App\Controller\MonSiteController::index

Entreprises:
  path: /entreprises
  controller: App\Controller\MonSiteController::pageEntreprises

Formations:
  path: /formations
  controller: App\Controller\MonSiteController::pageFormations

Stages:
  path: /stages
  controller: App\Controller\MonSiteController::pageStages

