index:
  path: /
  controller: App\Controller\DefaultController::accueil

pageEntreprises:
  path: /entreprises
  controller: App\Controller\DefaultController::entreprises

pageFormations:
  path: /formations
  controller: App\Controller\DefaultController::formations

pageStages:
  path: /stages
  controller: App\Controller\DefaultController::stages

