Accueil:
  path: /
  controller: App\Controller\MonSiteController::index

Entreprises:
  path: /entreprises
  controller: App\Controller\MonSiteController::pageEntreprises

Formations:
  path: /formations
  controller: App\Controller\MonSiteController::pageFormations

Stages:
  path: /stages/{id}
  controller: App\Controller\MonSiteController::pageStages

ListeStagesParEntreprise:
  path: /entreprises/{idEntreprise}
  controller: App\Controller\MonSiteController::ListeStagesParEntreprise

ListeStagesParFormation:
  path: /formations/{idFormation}
  controller: App\Controller\MonSiteController::ListeStagesParFormation
