Accueil:
  path: /{pageSelected<\d+>}
  controller: App\Controller\MonSiteController::index
  defaults:
        pageSelected: 1

Entreprises:
  path: /entreprises
  controller: App\Controller\MonSiteController::pageEntreprises

Formations:
  path: /formations
  controller: App\Controller\MonSiteController::pageFormations

Stages:
  path: /stages/{id}
  controller: App\Controller\MonSiteController::pageStages

ListeStagesParEntreprise:
  path: /entreprises/{idEntreprise}/{pageSelected<\d+>}
  controller: App\Controller\MonSiteController::ListeStagesParEntreprise
  defaults:
        pageSelected: 1

ListeStagesParFormation:
  path: /formations/{idFormation}/{pageSelected<\d+>}
  controller: App\Controller\MonSiteController::ListeStagesParFormation
  defaults:
        pageSelected: 1
